name: flutter_chat_demo
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.0.0

  # Analytics & Crashlytics
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

  # Authentication
  google_sign_in: ^6.2.1
  local_auth: ^3.0.0

  # Image handling
  photo_view: ^0.15.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  image_picker: ^1.2.0

  # UI & UX
  fluttertoast: ^9.0.0
  provider: ^6.1.0
  intl: ^0.20.0

  shared_preferences: ^2.5.0
  path_provider: ^2.1.0

  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.0

  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0

  permission_handler: ^12.0.0

  connectivity_plus: ^7.0.0
  http: ^1.5.0

  flutter_sound: ^9.16.0
  audio_session: ^0.2.2

  geolocator: ^14.0.2

  translator: ^1.0.0

  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/