name: flutter_chat_demo
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.0.3
  fluttertoast: ^9.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.2.1
  photo_view: ^0.15.0
  provider: ^6.1.5
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  timezone: ^0.10.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.32.1"